# Generated by Django 5.0 on 2024-01-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isDeliver',
            new_name='order_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paymentMethod',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveredAt',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postalCode',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
